### ISSUE TITLE
no `warp_in` method for OrdinalParamDef

### ISSUE THREAD

**Issue by zxytim** [FrederikDiehl/apsis#111]
I ran the following experiment:
```python
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# $File: issue.py
# $Date: Wed Apr 08 09:35:58 2015 +0800
# $Author: Xinyu Zhou <zxytim[at]gmail[dot]com>

import math

def f(p):
    return p


from apsis.models.parameter_definition import MinMaxNumericParamDef, \
    OrdinalParamDef

param_defs = {
    'p': OrdinalParamDef([1, 2])
}
from apsis.assistants.lab_assistant import PrettyLabAssistant
assistant = PrettyLabAssistant()
assistant.init_experiment("tutorial_experiment", "BayOpt", param_defs,
                          minimization=True)

i = 0
while True:
    candidate = assistant.get_next_candidate("tutorial_experiment")
    p = candidate.params['p']
    candidate.result = f(p)
    print i, p, candidate.result
    assistant.update("tutorial_experiment", candidate)

    best_cand = assistant.get_best_candidate("tutorial_experiment")

    print("Best result: " + str(best_cand.result))
    print("with parameters: " + str(best_cand.params))
    print('--------------------')
    i += 1

# assistant.plot_result_per_step(['tutorial_experiment'])


# vim: foldmethod=marker
```

and it raised an error:
```bash
/home/zxytim/.local/lib/python2.7/site-packages/GPy/util/linalg.py:48: UserWarning: warning: caught this exception:'module' object has no attribute '_dotblas'
  warnings.warn("warning: caught this exception:" + str(e))
2015-04-08 09:38:18,400 - apsis.utils.import_utils - WARNING - Module pymcmc could not be imported as it could not be found.
0 1 1
Best result: 1
with parameters: {'p': 1}
--------------------
1 1 1
Best result: 1
with parameters: {'p': 1}
--------------------
2 2 2
Best result: 1
with parameters: {'p': 1}
--------------------
3 2 2
Best result: 1
with parameters: {'p': 1}
--------------------
4 1 1
Best result: 1
with parameters: {'p': 1}
--------------------
5 1 1
Best result: 1
with parameters: {'p': 1}
--------------------
6 2 2
Best result: 1
with parameters: {'p': 1}
--------------------
7 1 1
Best result: 1
with parameters: {'p': 1}
--------------------
8 1 1
Best result: 1
with parameters: {'p': 1}
--------------------
9 2 2
Best result: 1
with parameters: {'p': 1}
--------------------
Traceback (most recent call last):
  File "issue.py", line 26, in <module>
    candidate = assistant.get_next_candidate("tutorial_experiment")
  File "/home/zxytim/.local/lib/python2.7/site-packages/apsis/assistants/lab_assistant.py", line 105, in get_next_candidate
    return self.exp_assistants[exp_name].get_next_candidate()
  File "/home/zxytim/.local/lib/python2.7/site-packages/apsis/assistants/experiment_assistant.py", line 128, in get_next_candidate
    self.optimizer.get_next_candidates(self.experiment))
  File "/home/zxytim/.local/lib/python2.7/site-packages/apsis/optimizers/bayesian_optimization.py", line 127, in get_next_candidates
    self._refit(experiment)
  File "/home/zxytim/.local/lib/python2.7/site-packages/apsis/optimizers/bayesian_optimization.py", line 158, in _refit
    warped_in = experiment.warp_pt_in(c.params)
  File "/home/zxytim/.local/lib/python2.7/site-packages/apsis/models/experiment.py", line 278, in warp_pt_in
    warped_in[name] = self.parameter_definitions[name].warp_in(value)
AttributeError: 'OrdinalParamDef' object has no attribute 'warp_in'
```
I skimmed over definition of OrdinalParamDef in models/parameter_definition.py and can not find 'warp_in' method in any of its superclasses. But in models/experiment.py around line 278:
```python
warped_in = {}                                                        
for name, value ∈ params.iteritems():                                 
    warped_in[name] = self.parameter_definitions[n ame].warp_in(value)
return warped_in                                                      
```
It seems that it assumed all parameter definitions have a 'warp_in' method. I think this might be a bug.

**Comment by FrederikDiehl** [comment]
Thank you for the bug report!
The issue is slightly complex in that the bayesian optimizer currently does not support ordinal parameters - see issue #19. This is due to a lack of good approaches we can use - we could either transform the ordinal parameters into a 0-1 hypercube representing a one-hot encoding of the category, or try finding a completely new approach. We just haven't had the time for that.
However, it definitely is a bug that we're not returning any message/error - the function already existed for checking whether an experiment was supported, and each optimizer has a list of supported parameter definitions, it just wasn't checked at runtime. Branch i111_exp_check has fixed that for both the bayesian optimizer and randomsearch.
In your case, the definition you're using
    'p': OrdinalParamDef([1, 2])
suggests to me that you do have information about the parameter (namely, that they are integers). In that case, you can use
    'p': FixedValueParamDef([1, 2])
which tells the optimizer that it can assume there to be two values, with the difference indicated by their actual values. So, for example, if you'd define FixedValueParamDef with [1, 2, 5, 10], the result for p=2 would be a better indicator for p=1 than for p=5.
If this is not the case (for example, p in [A, B]), you can either use RandomSearch, or you can run one instance of the optimizer per possible p. Both of these are not optimal, of course.

**Comment by zxytim** [comment]
Thanks for your reply.
In fact it is the latter case for me :(. Hope apsis will support categorial
data soon.

On Thu, Apr 9, 2015 at 6:59 PM, FrederikDiehl <notifications@github.com>
wrote:

> Thank you for the bug report!
> The issue is slightly complex in that the bayesian optimizer currently
> does not support ordinal parameters - see issue #19
> <https://github.com/FrederikDiehl/apsis/issues/19>. This is due to a lack
> of good approaches we can use - we could either transform the ordinal
> parameters into a 0-1 hypercube representing a one-hot encoding of the
> category, or try finding a completely new approach. We just haven't had the
> time for that.
> However, it definitely is a bug that we're not returning any message/error
> - the function already existed for checking whether an experiment was
> supported, and each optimizer has a list of supported parameter
> definitions, it just wasn't checked at runtime. Branch i111_exp_check has
> fixed that for both the bayesian optimizer and randomsearch.
> In your case, the definition you're using
> 'p': OrdinalParamDef([1, 2])
> suggests to me that you do have information about the parameter (namely,
> that they are integers). In that case, you can use
> 'p': FixedValueParamDef([1, 2])
> which tells the optimizer that it can assume there to be two values, with
> the difference indicated by their actual values. So, for example, if you'd
> define FixedValueParamDef with [1, 2, 5, 10], the result for p=2 would be a
> better indicator for p=1 than for p=5.
> If this is not the case (for example, p in [A, B]), you can either use
> RandomSearch, or you can run one instance of the optimizer per possible p.
> Both of these are not optimal, of course.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FrederikDiehl/apsis/issues/111#issuecomment-91194874>.
>



-- 
Xinyu Zhou
Department of Computer Science & Technology
Tsinghua University, Beijing, China
Mobile: +86 18810311452

**Comment by FrederikDiehl** [comment]
So do I. I'll update this issue once it does, so you'll get notified of the fact.

**Comment by FrederikDiehl** [comment]
With commit 7f700f347ae0d2c7625ed4a5664952619c88ad8e apsis also supports nominal parameters. The old (0.1) interface including categorical parameters is in the dev branch; the new, parallel-capable version in the server_client branch.
