### ISSUE TITLE
Optimization of EI always gets stuck in local extrema

### ISSUE THREAD

**Issue by andi1400** [FrederikDiehl/apsis#31]
At the moment we optimize EI with scypy.optimize.minimize. Tried several optimizer methods, all of them get stuck in local extrema.

Problem seems to be well known:
- the bergstra group reports on it http://papers.nips.cc/paper/4443-algorithms-for-hyper-parameter-optimization.pdf (page 3)
- http://www.icml2010.org/papers/297.pdf report about this, too
- the old spearmint package also seems to use grid search here if I understand their code right

Proposed optimization methods there
- grid search (probably not feasible)
- evolutionary algorithm

Other ideas
- random search, how many points?
- continue using SLSQP, L-BFGS-B and implement a random restart for them. How often?

**Comment by andi1400** [comment]
@andi1400 Document about new EI optimization. Implement optimize_restarts

**Comment by andi1400** [comment]
EI Opzimization Improved. We now have implemented EI gradient for use in BFGS optimization of EI. This optimization can be activated setting "acquisition_hyperparams":{"optimization": "bfgs"}.

It will work as follows:
* first random search with 1000 samples is executed
* the best result found in random search is used as a starting point in BFGS
* if BFGS optimization is successful in can only be better than the starting point (can be theoretically proven) => this result will be reported as maximium. In case BFGS was not successful the random search result will be used.

To be done here: Add multiple restarts to BFGS. Make BFGS to be the standard optimizer. Do a bit of performance evaluation to verify results.

**Comment by FrederikDiehl** [comment]
Closed with the new optimization. For details, see the commits referencing this issue.
