### ISSUE TITLE
PYMCMC requirement - add check if installed before import

### ISSUE THREAD

**Issue by andi1400** [FrederikDiehl/apsis#85]
something like this... Then also add check if imported before usage...

def module_exists(module_name):
    try:
        __import__(module_name)
    except ImportError:
        return False
    else:
        return True

**Comment by bayerj** [comment]
you can also use __import__ to not mess with global name spaces

On Friday, January 30, 2015, Andreas Jauch <notifications@github.com> wrote:

> something like this... Then also add check if imported before usage...
>
> def module_exists(module_name):
> try:
> *import*(module_name)
> except ImportError:
> return False
> else:
> return True
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FrederikDiehl/apsis/issues/85>.
>


-- 
Q: Why is this email five sentences or less?
A: http://five.sentenc.es


Dipl. Inf. Justin Bayer
Lehrstuhl für Robotik und Echtzeitsysteme, Technische Universität München
http://www6.in.tum.de/Main/Bayerj
